name: Push Docker Image

on:
  push:
    branches:
      - master
      - main
      - stage
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short=7 ${{ github.sha }})" >> "$GITHUB_OUTPUT"

      - name: Build the Docker image
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/chaskiq
        run: |
          docker build --build-arg APP_ENV=production \
               --build-arg RUBY_VERSION=3.3.5 \
               --build-arg PG_MAJOR=15 \
               --build-arg NODE_MAJOR=16 \
               --build-arg YARN_VERSION=1.13.0 \
               --build-arg BUNDLER_VERSION=2.4.10 \
               -t "$IMAGE" \
               .

      - name: Tag and Push Docker image
        if: github.event_name == 'push'
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/chaskiq
        run: |
          docker tag "$IMAGE" "$IMAGE:${{ steps.vars.outputs.short_sha }}"
          docker push "$IMAGE:${{ steps.vars.outputs.short_sha }}"

      - name: Tag LATEST and Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/chaskiq
        run: |
          docker tag "$IMAGE" "$IMAGE:latest"
          docker push "$IMAGE:latest"

      - name: Tag RELEASE and Push Docker image
        if: github.event_name == 'release'
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/chaskiq
        run: |
          docker tag "$IMAGE" "$IMAGE:${{ github.ref_name }}"
          docker push "$IMAGE:${{ github.ref_name }}"
